[workspace]
members = ["."]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.82"
authors = ["SWE Engineering Labs"]
repository = "https://github.com/sweengineeringlabs/edge"
