//! SAF layer — internal implementation.

mod grpc;

#[cfg(test)]
mod tests;

pub use edge_security_runtime::TLS_SVC;
pub use grpc::{
    GRPC_SERVER_BUILD_SVC, GRPC_SERVER_CONFIG_BUILDER_SVC, GRPC_SERVER_CONFIG_BUILD_SVC,
    GRPC_SERVER_CONFIG_OPS_SVC, GRPC_SERVER_CONFIG_SVC, GRPC_SERVER_MANAGE_SVC,
    GRPC_SERVER_OBSERVER_OPS_SVC, GRPC_SERVER_OBSERVER_SVC, GRPC_SERVER_SVC,
    GRPC_SERVER_SVC_OPS_SVC, STATUS_CODE_CONVERT_SVC,
};
